### ISSUE TITLE
What type of 'checksum' is it?

### ISSUE THREAD

**Issue by RonCam** [phux/pomogoro#6]
I put both the 'checksums' file and the binary into my download subdirectory, so we have this:
```
~/Downloads/Pomogoro ToPyDo add-on > ls
checksums.txt  pomogoro_1.3.0_Linux_i386.tar.gz
```
and then, ran this from terminal:
```
~/Downloads/Pomogoro ToPyDo add-on > sha256sum -c pomogoro_1.3.0_Linux_i386.tar.gz
sha256sum: pomogoro_1.3.0_Linux_i386.tar.gz: no properly formatted SHA256 checksum lines found
```
Why am I seeing this: **no properly formatted SHA256 checksum lines found**:   Is the type of checksum the problem and if yes, did I miss it, somewhere??

**Comment by jmollowitz-h24** [comment]
Hey,
SHA256 is used for the checksum generation, indeed.
The problem lies in your usage of `sha256sum`:
If you check via  `-c` you have provide the checksums.txt, not the archive itself.
Example with the Linux_i386.tar.gz and checksums.txt in same directory:
```sha256sum -c checksums.txt 2>&1 | grep OK 
pomogoro_1.3.0_Linux_i386.tar.gz: OK
```
The other option is to omit the `-c` flag, specify the archive name and compare the sums manually: 
```~/Downloads% sha256sum pomogoro_1.3.0_Linux_i386.tar.gz 
0a74ebf74747934fd0e6dc98642573e5b3b962009c3a7a521fd7818222b7f8e1  pomogoro_1.3.0_Linux_i386.tar.gz
~/Downloads% cat checksums.txt                         
0a74ebf74747934fd0e6dc98642573e5b3b962009c3a7a521fd7818222b7f8e1 pomogoro_1.3.0_Linux_i386.tar.gz
[...]
```

**Comment by RonCam** [comment]
@jmollowitz-h24 
Thanks!  

Working perfectly now, and I have updated my _Gnote_ entry for terminal checksums to emphasize the point you made.

I found detail on the syntax [here](https://www.reddit.com/r/linux4noobs/comments/759t8g/what_does_sha256sum_c_sha256sums_21_grep_ok_do/).
