### ISSUE TITLE
Program displays an extraneous line in Todos area, ending with a terminal prompt

### ISSUE THREAD

**Issue by RonCam** [phux/pomogoro#7]
Pomogoro is _almost_ running in a terminal window.  Almost, because the display aborts by inserting an extraneous line at the top, that concludes with a terminal prompt.  As you may see, I had to hit CRTL-C to break out of it:

```
┌─Todos─────────────────────────────────────────────┐─Timer──────────────────────────────────────────────
│2019/01/09 22:43:24 Line does not have 2 | separators:  ING (press enter on a todo to start)
ron@ron-gnulinux:~ > ^C 
```

Where is this line coming from?  **2019/01/09** is today's date, but there is no line in TODO.TXT with this date.  Does this indicate my TODO.TXT file is corrupt?  But, it looks OK ...

This is how I'm executing the program, as copied from the terminal entry:
`~ > pomogoro --config /home/ron/Todo/Pomogoro/config.toml`
and, this is what the config file contains:
```
# config.toml
TodoFile = "/home/ron/Sync/ToDoTxt-desktop/todo.txt" # containing the tasks you want to track
LogFile = "/home/ron/Todo/Pomogoro/pomogoro.log" # tracking log file
BreakDuration = 5 # in minutes
PomodoroEnabled = true # whether to use pomodoro timer or not
PomodoroDuration = 25 # in minutes
LogIdleTime = true # also log idle times
LogBreakTime = true # also log breaks
```
Please let me know if additional information would help to troubleshoot this.

**Comment by phux** [comment]
The problem is your log file @ `LogFile = "/home/ron/Todo/Pomogoro/pomogoro.log"`
The error message is related to the formatting of a line in there - from the message, the line only contains "ING".
This does not look like `pomogoro` has written to this file.
Did you maybe edit this file on accident?
You can quickly test it by doing
```sh
mv /home/ron/Todo/Pomogoro/pomogoro.log /home/ron/Todo/Pomogoro/pomogoro.log.bkp
```
`pomogoro` will then create a new log file on the first finished or canceled tracking event.

**Comment by RonCam** [comment]
Thanks for the quick and accurate help!

I followed your directions and now the program starts perfectly.

The file pomogoro.log was created in the file manager (Dophin) with the create a New File command, and when opened in the text editor, it appeared to be completely blank.

But, renaming it to a backup and then letting pomogoro recreate it on the first run -- has taken care of whatever problem may have existed.
