### ISSUE TITLE
Add option to only display tasks for a specific tag

### ISSUE THREAD

**Issue by RonCam** [phux/pomogoro#8]
I'm not yet able to run the program (until earlier Issue is resolved) but I am looking forward to that time and wondering if this is the case?  It seems to be, from the illustration, but I don't see it actually stated, in the documentation.  

I'm hoping it works this way, otherwise I would intend make a suggestion that it be incorporated ...

**Comment by phux** [comment]
The screenshot you are referring to just shows my separate pomogoro todo.txt that contains only tasks with `+pomogoro` tags :)

In general: displaying only `+pomogoro` tagged tasks would be a new feature, but only as an optional one.

**Comment by RonCam** [comment]
Ah! I see, you creating a separate todo.txt file for the exclusive used of pomogoro.  And so, the +pomogoro tag in the screenshot actually has no function, that affects the operation of pomogoro?

If there were a task-name filter, it might either be 'baked in' _or_ optional, since I think that average user (excluding, of course, the developer) wouldn't be running a project with that name.  So for the average user, that enhancement would just remain dormant until a +pomogoro tag appears.

Until I get pomogoro running, at this point, I really don't know if it would be more user-friendly to move tasks back-and-forth between pomogoro-status and normal todo.txt file status, or to have this happen automatically by means of a filter.

Using the topydo (python front-end for _todo.txt_ task management) I think it's a relatively minor task to switch or add new project names, into existing Tasks.

I can't quite envision a way, other than manually-retyping Tasks in a new terminal instance, how existing tasks could seamlessly be moved back-and-forth from one todo.txt file to another?

Have you devised a way of doing this, that's easier or faster than retyping a new project-name into an existing task?  Or, in actual use, have you found this to be a non-issue?

**Comment by RonCam** [comment]
Just a thought:
If a user has a really big todo.txt file with pomogoro tasks 'buried in it' at various locations, and if they were [Tagged](https://cdn.rawgit.com/bram85/topydo/master/doc/Documentation.html?fbclid=IwAR2YNA1enDMeGM693l1Ii-t3G750h7afiBAQPZcyb7ScbT0yc7vx37ZqqCE#Tag) with, for example, _pomo:0_, it should be possible for a determined user to [pre-process that file](https://stackoverflow.com/a/52983290) with _grep_, _awk_ or _sed_, with output directed to a new todo.txt file to which pomogoro would be directed, in its config file.

I might even enjoy doing that, at least once or twice!  But I wonder if more users would be interested if asimilar functionality could be incorporated into the program?

**Comment by RonCam** [comment]
This is working, and it's not as complicated as I initially thought it might be:
`grep -w 'pomotask:0' todo.txt > pomotask.txt`
The Tag I settled on is _pomotask:0_, to be inserted or removed, as needed.  

The pomogoro configuration file is modified to point at the above file, which now contains only pomogoro tasks.

I'm thinking of starting pomogoro with a script that first runs this, and then pomogoro, including the config file path -- to avoid potential errors associated with typing it out, each time.

The result is to clear irrelevant, non-task Reminders (e.g., appointments, birthdays, etc.) out of the 'ToDos' panel.  Now, pomogoro may be used on the user's main todo.txt file, and not a special one with just a few task-related entries.

**Comment by existme** [comment]
Hi, I am also wondering if that's a possibility? I have a very large todo file (more than 400 lines), since pomogoro doesn't offer any command line interaction, it's hard for me to find the specific task that I want to apply Pomodoro.
I would rather be able to filter the text based on a parameter provided to pomogoro to list those... 

For example:
```
pomogoro -t @pomodoro
```

I understand your suggested way can work but I am also thinking `pomogoro` can interact with the todo item in feature and for example mark it as done.
